namespace Banog.UI.Localization;

/// <summary>
/// Tous les textes de l'interface, français et anglais côte à côte.
///
/// Une seule table, une seule ligne par texte : une traduction qui manque ou qui dérive
/// se voit à la lecture, sans avoir à comparer deux fichiers. Les clés portent toutes un
/// souligné, ce qui les distingue des clés de couleurs de la palette — les deux vivent
/// dans les mêmes ressources d'application.
///
/// Le XAML lit ces textes par <c>{DynamicResource Clé}</c>, le C# par <see cref="Loc"/>.
/// </summary>
internal static class Texts
{
    public static (string Key, string Fr, string En)[] All =>
    [
        // ---- Application, barre latérale ------------------------------------------------
        ("App_Title", "Banog — rangement automatique", "Banog — automatic filing"),
        ("App_Tagline", "Rangement automatique", "Automatic filing"),

        ("Nav_Monitoring", "Surveillance", "Monitoring"),
        ("Nav_Monitoring_Tip", "Ce que Banog surveille et ce qu'il a fait.",
            "What Banog watches, and what it has done."),
        ("Nav_Rules", "Règles", "Rules"),
        ("Nav_Rules_Tip", "Écrire les dossiers surveillés et les règles.",
            "Set the watched folders and the rules."),
        ("Nav_Settings", "Paramètres", "Settings"),
        ("Nav_Settings_Tip", "Apparence et réglages de l'application.",
            "Appearance and application settings."),

        ("Side_Start", "Démarrer", "Start"),
        ("Side_Pause", "Mettre en pause", "Pause"),
        ("Side_RunNow", "Ranger maintenant", "Tidy up now"),
        ("Side_RunNow_Tip", "Applique les règles aux fichiers déjà présents dans les dossiers surveillés.",
            "Applies the rules to the files already sitting in the watched folders."),
        ("Side_Unsaved", "Sauvegarde en attente", "Save pending"),
        ("Side_Save", "Enregistrer maintenant", "Save now"),

        // ---- Zone de notification --------------------------------------------------------
        ("Tray_Open", "Ouvrir Banog", "Open Banog"),
        ("Tray_Quit", "Quitter", "Quit"),

        ("State_Running", "En marche", "Running"),
        ("State_Paused", "En pause", "Paused"),
        ("State_Watching_One", "{0} dossier sous surveillance", "{0} folder watched"),
        ("State_Watching_Many", "{0} dossiers sous surveillance", "{0} folders watched"),
        ("State_NothingWatched", "Rien n'est surveillé pour le moment", "Nothing is being watched yet"),

        // ---- Surveillance ---------------------------------------------------------------
        ("Mon_Title", "Surveillance", "Monitoring"),
        ("Mon_Subtitle", "Ce que Banog surveille, les règles en place, et ce qu'il a fait.",
            "What Banog watches, the rules in place, and what it has done."),
        ("Mon_Metric_Files", "fichiers rangés depuis l'ouverture", "files filed since launch"),
        ("Mon_Metric_Errors", "erreurs", "errors"),
        ("Mon_Metric_Rules", "règles actives", "active rules"),
        ("Mon_Metric_Folders", "dossiers surveillés", "watched folders"),
        ("Mon_RulesHeader", "RÈGLES EN PLACE", "RULES IN PLACE"),
        ("Mon_Rules_Empty",
            "Aucune règle pour l'instant.\n\nUne règle, c'est « si un fichier ressemble à ceci, fais cela ».",
            "No rules yet.\n\nA rule says “if a file looks like this, do that”."),
        ("Mon_CreateFirstRule", "Créer une première règle", "Create a first rule"),
        ("Mon_Edit", "Modifier", "Edit"),
        ("Mon_ActivityHeader", "CE QUI S'EST PASSÉ", "WHAT HAPPENED"),
        ("Mon_Activity_Last", "dernier : {0}", "last: {0}"),
        ("Mon_Clear", "Vider", "Clear"),
        ("Mon_Clear_Tip", "Efface l'affichage et remet les compteurs à zéro. Ne touche à aucun fichier.",
            "Clears the list and resets the counters. Touches no file."),
        ("Mon_Activity_Empty",
            "Rien pour l'instant.\n\nChaque fichier rangé apparaîtra ici, avec l'heure et la règle qui s'est appliquée.",
            "Nothing yet.\n\nEvery filed file will show up here, with the time and the rule that applied."),
        ("Mon_Activity_None", "aucun", "none"),

        // ---- Règles ---------------------------------------------------------------------
        ("Rules_Title", "Règles", "Rules"),
        ("Rules_Subtitle", "Les dossiers à surveiller, et ce qu'il faut faire des fichiers qui y arrivent.",
            "The folders to watch, and what to do with the files landing in them."),
        ("Rules_FoldersHeader", "1. DOSSIERS À SURVEILLER", "1. FOLDERS TO WATCH"),
        ("Rules_ChooseFolder", "+ Choisir un dossier", "+ Choose a folder"),
        ("Rules_RemoveFolder", "Retirer", "Remove"),
        ("Rules_Folders_Empty",
            "Aucun dossier surveillé.\n\nChoisissez un dossier — vos téléchargements, par exemple — et Banog surveillera ce qui y arrive.",
            "No folder watched.\n\nChoose a folder — your downloads, for instance — and Banog will watch what lands there."),
        ("Rules_IncludeSubfolders", "Y compris les sous-dossiers", "Including subfolders"),
        ("Rules_RulesHeader", "2. RÈGLES", "2. RULES"),
        ("Rules_NewRule", "+ Nouvelle règle", "+ New rule"),
        ("Rules_Duplicate", "Dupliquer", "Duplicate"),
        ("Rules_Delete", "Supprimer", "Delete"),
        ("Rules_List_Empty",
            "Aucune règle.\n\nUne règle, c'est « si un fichier ressemble à ceci, fais cela ».",
            "No rules.\n\nA rule says “if a file looks like this, do that”."),
        ("Rules_ToggleRule_Tip", "Activer ou désactiver cette règle", "Turn this rule on or off"),
        ("Rules_SelectPrompt", "Sélectionnez une règle à gauche, ou créez-en une.",
            "Pick a rule on the left, or create one."),
        ("Rules_NewRule_Name", "Nouvelle règle", "New rule"),
        ("Rules_Copy_Suffix", "{0} (copie)", "{0} (copy)"),

        ("Rule_NameWatermark", "Nom de la règle", "Rule name"),
        ("Rule_If", "SI", "IF"),
        ("Rule_IfSuffix", "de ces conditions sont remplies :", "of these conditions are met:"),
        ("Rule_NoConditions", "Sans condition, cette règle ne s'appliquera à aucun fichier.",
            "With no condition, this rule will never apply to any file."),
        ("Rule_Unless", "sauf si", "unless"),
        ("Rule_Unless_Tip", "Inverse cette condition.", "Flips this condition."),
        ("Rule_RemoveCondition_Tip", "Retirer cette condition", "Remove this condition"),
        ("Rule_AddCondition", "+ Ajouter cette condition", "+ Add this condition"),
        ("Rule_Then", "ALORS", "THEN"),
        ("Rule_NoActions", "Aucune action : la règle repérerait les fichiers sans rien en faire.",
            "No action: the rule would spot files and do nothing with them."),
        ("Rule_RemoveAction_Tip", "Retirer cette action", "Remove this action"),
        ("Rule_AddAction", "+ Ajouter cette action", "+ Add this action"),
        ("Rule_Test", "Essayer sur un fichier…", "Try it on a file…"),
        ("Rule_Test_Hint", "Montre ce qui se passerait. Ne touche à rien.",
            "Shows what would happen. Touches nothing."),
        ("Rule_StopProcessing", "Quand cette règle s'applique, ne pas essayer les règles suivantes",
            "When this rule applies, don't try the following rules"),

        ("Rules_Back", "‹ Toutes les règles", "‹ All rules"),
        ("Rules_Count_One", "1 règle", "1 rule"),
        ("Rules_Count_Many", "{0} règles", "{0} rules"),

        // ---- Flux de la règle -------------------------------------------------------------
        ("Flow_Folders", "Dossiers surveillés", "Watched folders"),
        ("Flow_Folders_Note", "Ces dossiers valent pour toutes les règles.",
            "These folders apply to every rule."),
        ("Flow_Trigger_Title", "Fichier détecté", "File detected"),
        ("Flow_Trigger_Note",
            "Le flux part d'ici : tout fichier qui arrive dans un dossier surveillé y entre.",
            "The flow starts here: every file landing in a watched folder enters it."),
        ("Flow_AddCondition", "Ajouter une condition", "Add a condition"),
        ("Flow_AddAction", "Ajouter une action", "Add an action"),
        ("Flow_Gate_Note", "Comment les conditions se combinent-elles ?",
            "How do the conditions combine?"),
        ("Flow_Gate_Suffix", "des conditions doivent être remplies.", "of the conditions must be met."),
        ("Flow_Inspector_Empty", "Choisissez une étape du flux pour la régler.",
            "Pick a step in the flow to set it up."),
        ("Flow_Choose_Condition", "Quelle condition ajouter ?", "Which condition to add?"),
        ("Flow_Choose_Action", "Quelle action ajouter ?", "Which action to add?"),
        ("Flow_Remove", "Retirer cette étape", "Remove this step"),
        ("Flow_MoveEarlier", "‹ Plus tôt", "‹ Earlier"),
        ("Flow_MoveLater", "Plus tard ›", "Later ›"),
        ("Flow_Order_Note", "Les actions s'exécutent de gauche à droite.",
            "Actions run from left to right."),
        ("Flow_ZoomIn", "Agrandir", "Zoom in"),
        ("Flow_ZoomOut", "Réduire", "Zoom out"),
        ("Flow_ZoomReset", "Taille réelle", "Actual size"),
        ("Flow_Hint", "Cliquez sur une étape pour ouvrir ses paramètres. Molette pour zoomer, glissez le fond pour déplacer.",
            "Click a step to open its settings. Wheel to zoom, drag the background to move."),
        ("Flow_Step_Condition", "Condition", "Condition"),
        ("Flow_Step_Action", "Action", "Action"),

        // ---- Paramètres -----------------------------------------------------------------
        ("Set_Title", "Paramètres", "Settings"),
        ("Set_Subtitle", "Réglages de l'application. Ils ne changent aucune règle.",
            "Application settings. They change no rule."),
        ("Set_Appearance", "APPARENCE", "APPEARANCE"),
        ("Set_Theme", "Thème", "Theme"),
        ("Set_Theme_Note",
            "« Windows » suit le réglage clair/sombre du système. Le thème s'applique aussitôt et n'a pas besoin d'être enregistré.",
            "“Windows” follows the system light/dark setting. The theme applies at once and needs no saving."),
        ("Set_Language_Header", "LANGUE", "LANGUAGE"),
        ("Set_Language", "Langue", "Language"),
        ("Set_Language_Note",
            "« Windows » suit la langue du système : français si Windows est en français, anglais sinon. Le changement s'applique aussitôt et n'a pas besoin d'être enregistré.",
            "“Windows” follows the system language: French if Windows is in French, English otherwise. The change applies at once and needs no saving."),
        ("Set_Detection", "DÉTECTION DES FICHIERS", "FILE DETECTION"),
        ("Set_Wait", "Attendre", "Wait"),
        ("Set_WaitSuffix", "millisecondes avant de traiter un fichier",
            "milliseconds before handling a file"),
        ("Set_Detection_Note",
            "Ce délai laisse le temps à un téléchargement de se terminer. Entre 100 et 30 000 ms. Le changement prend effet au prochain démarrage de Banog.",
            "This delay gives a download time to finish. Between 100 and 30,000 ms. Takes effect the next time Banog starts."),
        ("Set_ConfigFile", "FICHIER DE CONFIGURATION", "CONFIGURATION FILE"),
        ("Set_ConfigFile_Note",
            "Vos dossiers, vos règles et vos préférences sont enregistrés dans ce fichier. Copiez-le pour les retrouver sur un autre poste.",
            "Your folders, rules and preferences are saved in this file. Copy it to carry them to another machine."),

        // ---- Mises à jour -------------------------------------------------------------
        ("Update_Title", "Mise à jour disponible", "Update available"),
        ("Update_Body", "Une nouvelle version ({0}) est prête à être installée.",
            "A new version ({0}) is ready to install."),
        ("Update_View", "Voir", "View"),
        ("Update_Dismiss", "Plus tard", "Later"),
        ("Update_UpToDate", "Banog est à jour.", "Banog is up to date."),
        ("Update_Found", "Nouvelle version {0} disponible.", "New version {0} is available."),
        ("Set_Updates", "MISES À JOUR", "UPDATES"),
        ("Set_Version", "Version installée", "Installed version"),
        ("Set_CheckUpdates", "Vérifier les mises à jour", "Check for updates"),
        ("Set_Updates_Note",
            "Banog consulte GitHub de lui-même, une fois par jour, et vous prévient ici sans rien installer. La surveillance en arrière-plan continue de tourner.",
            "Banog checks GitHub on its own, once a day, and tells you here without installing anything. Background watching keeps running."),

        ("Set_Startup", "DÉMARRAGE", "STARTUP"),
        ("Set_BackgroundStartup", "Démarrage en arrière-plan", "Background startup"),
        ("Set_BackgroundStartup_Note",
            "Banog démarre toujours avec Windows, sans fenêtre. La surveillance continue depuis la zone de notification.",
            "Banog always starts with Windows, without a window. Watching continues from the notification area."),

        ("Theme_System", "Thème : Windows", "Theme: Windows"),
        ("Theme_Light", "Thème : clair", "Theme: light"),
        ("Theme_Dark", "Thème : sombre", "Theme: dark"),

        ("Lang_System", "Langue : Windows", "Language: Windows"),
        ("Lang_French", "Français", "Français"),
        ("Lang_English", "English", "English"),

        // ---- Conditions -----------------------------------------------------------------
        ("Cond_Type", "Le type de fichier", "The file type"),
        ("Cond_Type_None", "Aucun type choisi : cette condition ne retiendrait aucun fichier.",
            "No type chosen: this condition would match no file."),
        ("Cond_Name", "Le nom", "The name"),
        ("Cond_Name_CaseSensitive", "Tenir compte des majuscules", "Match upper and lower case"),
        ("Cond_Date", "La date", "The date"),
        ("Cond_Size", "La taille du fichier", "The file size"),
        ("Cond_Source", "Le fichier vient de", "The file comes from"),
        ("Cond_Source_IncludeSub", "Y compris ses sous-dossiers", "Including its subfolders"),
        ("Cond_Unsupported",
            "Créé par une version plus récente. Non modifiable ici, mais conservé tel quel.",
            "Created by a newer version. Not editable here, but kept as is."),

        ("Types_ClearAll", "Tout retirer", "Remove all"),
        ("Types_Search_Watermark", "Chercher un type : pdf, photo, vidéo, archive…",
            "Search a type: pdf, photo, video, archive…"),
        ("Types_Close", "Fermer", "Close"),
        ("Types_NoResults", "Aucun type connu ne correspond à cette recherche.",
            "No known type matches this search."),
        ("Types_AddAll", "tout ajouter", "add all"),
        ("Types_Remove_Tip", "Retirer ce type", "Remove this type"),
        ("Types_Custom_Tip", "Une extension absente de la liste reste utilisable.",
            "An extension missing from the list stays usable."),
        ("Types_Pick", "Choisir des types de fichiers…", "Choose file types…"),
        ("Types_AddAnother", "Ajouter un autre type…", "Add another type…"),
        ("Types_Add", "Ajouter un type…", "Add a type…"),
        ("Types_AddCustom", "Ajouter « .{0} » quand même", "Add “.{0}” anyway"),

        // ---- Actions --------------------------------------------------------------------
        ("Act_MoveTo", "Déplacer dans", "Move into"),
        ("Act_CopyTo", "Copier dans", "Copy into"),
        ("Act_Rename", "Renommer", "Rename"),
        ("Act_CreateDirs", "Créer le dossier s'il n'existe pas", "Create the folder if it doesn't exist"),
        ("Act_OnConflict", "Si un fichier du même nom existe :", "If a file with the same name exists:"),
        ("Act_Delete_Recycle", "Mettre à la corbeille (récupérable)", "Send to the recycle bin (recoverable)"),
        ("Act_Delete_Warning",
            "Sans la corbeille, le fichier est effacé sans retour possible. Essayez la règle avant de l'activer.",
            "Without the recycle bin, the file is erased with no way back. Try the rule before turning it on."),
        ("Act_Recycle_Note", "Le fichier sera envoyé à la corbeille Windows et restera récupérable.",
            "The file will be sent to the Windows recycle bin and can be recovered."),
        ("Act_Run", "Lancer", "Run"),
        ("Act_Run_With", "avec", "with"),
        ("Act_Run_Args", "arguments (facultatif)", "arguments (optional)"),
        ("Act_Run_Wait", "Attendre la fin avant de continuer", "Wait for it to finish before continuing"),
        // Noms des actions dans le sélecteur : un verbe seul, pas une phrase à trous.
        ("Act_MoveKind", "Déplacer", "Move"),
        ("Act_CopyKind", "Copier", "Copy"),
        ("Act_DeleteKind", "Supprimer", "Delete"),
        ("Act_RecycleKind", "Mettre à la corbeille", "Send to the recycle bin"),
        ("Act_RunKind", "Exécuter une commande", "Run a command"),

        ("Act_Unsupported",
            "Créée par une version plus récente. Non modifiable ici, mais conservée telle quelle.",
            "Created by a newer version. Not editable here, but kept as is."),

        ("Common_Browse", "Parcourir…", "Browse…"),
        ("Common_ChooseFolder", "Choisir un dossier…", "Choose a folder…"),
        ("Common_ChooseProgram", "Choisir un programme…", "Choose a program…"),
        ("Common_ProgramFilter", "Programmes", "Programs"),
        ("Common_PickFolderTitle", "Dossier à surveiller", "Folder to watch"),
        ("Common_PickDestination", "Dossier de destination", "Destination folder"),
        ("Common_PickSourceFolder", "Dossier d'origine", "Source folder"),
        ("Common_PickProgramTitle", "Programme à exécuter", "Program to run"),
        ("Common_PickSampleFile", "Choisir un fichier d'exemple", "Choose a sample file"),
        ("Common_EmptyFolder", "(dossier vide)", "(empty folder)"),

        // ---- Composition d'un nom -------------------------------------------------------
        ("Tpl_Hint_Name",
            "Composez le nouveau nom, morceau par morceau. Le point et l'extension restent à la fin.",
            "Build the new name piece by piece. The dot and the extension stay at the end."),
        ("Tpl_Hint_Folder",
            "Sous-dossier, facultatif. Laissez vide pour tout ranger dans le dossier choisi.",
            "Subfolder, optional. Leave empty to put everything in the chosen folder."),
        ("Tpl_OpenPalette", "＋ Ranger dans un sous-dossier (par date, par type…)",
            "＋ File into a subfolder (by date, by type…)"),
        ("Tpl_Preview_Name", "Donnerait", "Would give"),
        ("Tpl_Preview_Folder", "Rangerait dans", "Would file into"),
        ("Tpl_Preview_Sample", "— sur l'exemple {0}", "— for the sample {0}"),
        ("Tpl_SampleName", "rapport-annuel.pdf", "annual-report.pdf"),
        ("Tpl_SampleFolder", @"C:\Utilisateurs\vous\Téléchargements", @"C:\Users\you\Downloads"),
        ("Tpl_Drag_Tip", "Glissez pour déplacer ce morceau", "Drag to move this piece"),
        ("Tpl_Remove_Tip", "Retirer ce morceau", "Remove this piece"),
        ("Tpl_Text_Watermark", "texte", "text"),
        ("Tpl_Empty", "Ajoutez des morceaux avec les boutons ＋ ci-dessous.",
            "Add pieces with the ＋ buttons below."),
        ("Tpl_Ext_Original", "extension d'origine", "original extension"),
        ("Tpl_Ext_Original_Tip",
            "L'extension est toujours reprise du fichier d'origine et ne peut pas être modifiée.",
            "The extension is always taken from the original file and cannot be changed."),
        ("Tpl_Advanced_Hint",
            "Les mots entre accolades sont remplacés par les informations du fichier : {nom}, {extension}, {date}, {date:yyyy}, {modification}, {dossier}, {compteur:000}. L'extension d'origine est toujours conservée.",
            "Words in braces are replaced by the file's own details: {name}, {ext}, {date}, {date:yyyy}, {modified}, {folder}, {counter:000}. The original extension is always kept."),
        ("Tpl_Advanced_On", "Écrire le gabarit à la main", "Write the template by hand"),
        ("Tpl_Advanced_Off", "Revenir aux morceaux", "Back to the pieces"),

        ("Part_Literal", "Texte", "Text"),
        ("Part_Name", "Nom", "Name"),
        ("Part_Extension", "Extension", "Extension"),
        ("Part_Created", "Date de création", "Creation date"),
        ("Part_Modified", "Date de modification", "Modification date"),
        ("Part_Today", "Date du jour", "Today's date"),
        ("Part_Counter", "Numéro", "Number"),
        ("Part_Folder", "Dossier d'origine", "Source folder"),
        ("Part_FullName", "Nom avec extension", "Name with extension"),
        ("Part_Add", "＋ {0}", "＋ {0}"),

        ("Fmt_Ymd", "année-mois-jour", "year-month-day"),
        ("Fmt_Ym", "année-mois", "year-month"),
        ("Fmt_Y", "année seule", "year only"),
        ("Fmt_M", "mois seul", "month only"),
        ("Fmt_D", "jour seul", "day only"),
        ("Fmt_Compact", "sans séparateur", "no separator"),
        ("Fmt_WithTime", "avec l'heure", "with the time"),

        // ---- Résumés de règles ----------------------------------------------------------
        ("Sum_NoConditions", "Aucune condition — cette règle ne s'applique jamais.",
            "No condition — this rule never applies."),
        ("Sum_And", " et ", " and "),
        ("Sum_Or", " ou ", " or "),
        ("Sum_Arrow", " → ", " → "),
        ("Sum_NoAction", "aucune action", "no action"),
        ("Sum_Then", ", puis ", ", then "),
        ("Sum_Unless", "sauf si {0}", "unless {0}"),

        ("Desc_Type", "le type est {0}", "the type is {0}"),
        ("Desc_Type_Not", "le type n'est pas {0}", "the type is not {0}"),
        ("Desc_Name", "le nom {0} « {1} »", "the name {0} “{1}”"),
        ("Desc_Date_Duration", "la date {0} {1} {2} {3}", "the {0} date {1} {2} {3}"),
        ("Desc_Date_Instant", "la date {0} {1} {2}", "the {0} date {1} {2}"),
        ("Desc_Size", "la taille {0} {1} {2}", "the size {0} {1} {2}"),
        ("Desc_Source", "le fichier vient de « {0} »", "the file comes from “{0}”"),
        ("Desc_Unsupported_Cond", "condition « {0} »", "“{0}” condition"),
        ("Desc_Move", "déplacer vers {0}", "move to {0}"),
        ("Desc_Copy", "copier vers {0}", "copy to {0}"),
        ("Desc_Rename", "renommer, par ex. « {0} »", "rename, e.g. “{0}”"),
        ("Desc_Rename_Plain", "renommer", "rename"),
        ("Desc_Recycle", "mettre à la corbeille", "send to the recycle bin"),
        ("Desc_Delete", "supprimer définitivement", "delete permanently"),
        ("Desc_Run", "exécuter {0}", "run {0}"),
        ("Desc_Unsupported_Act", "action « {0} »", "“{0}” action"),
        ("Desc_NotEditable", "Non éditable ({0})", "Not editable ({0})"),
        ("Desc_Placeholder", "…", "…"),

        ("Trigger_None", "n'a rien traité", "handled nothing"),
        ("Trigger_One", "1 fichier traité", "1 file handled"),
        ("Trigger_Many", "{0} fichiers traités", "{0} files handled"),
        ("Rule_Active", "active", "on"),
        ("Rule_Disabled", "désactivée", "off"),

        // ---- Messages d'état ------------------------------------------------------------
        ("Status_Ready", "Prêt.", "Ready."),
        ("Status_Saved", "Enregistré dans {0}", "Saved to {0}"),
        ("Status_AutoSaved", "Sauvegarde automatique dans {0}", "Automatically saved to {0}"),
        ("Status_SaveFailed", "Sauvegarde impossible : {0}", "Could not save: {0}"),
        ("Status_ThemeFailed", "Préférence non enregistrée : {0}", "Preference not saved: {0}"),
        ("Status_FolderAlready", "Ce dossier est déjà surveillé.", "This folder is already watched."),
        ("Status_ChooseFolder", "Commencez par choisir un dossier à surveiller.",
            "Start by choosing a folder to watch."),
        ("Status_CreateRule", "Créez une règle pour dire quoi faire des fichiers qui arrivent.",
            "Create a rule to say what to do with arriving files."),
        ("Status_Counts", "{0}, {1}.", "{0}, {1}."),
        ("Status_Rules_One", "1 règle", "1 rule"),
        ("Status_Rules_Many", "{0} règles", "{0} rules"),
        ("Status_Folders_One", "1 dossier surveillé", "1 folder watched"),
        ("Status_Folders_Many", "{0} dossiers surveillés", "{0} folders watched"),
        ("Status_Watching", "Surveillance active.", "Watching."),
        ("Status_Stopped", "Surveillance en pause.", "Watching paused."),
        ("Status_RunNow", "Passage sur les fichiers déjà présents.", "Going over the files already there."),

        ("Test_Gone", "Ce fichier n'existe plus.", "This file no longer exists."),
        ("Test_Matches", "La règle s'applique. {0}", "The rule applies. {0}"),
        ("Test_NoMatch", "La règle ne s'applique pas à « {0} ».", "The rule does not apply to “{0}”."),
        ("Test_Failed", "Essai impossible : {0}", "Could not try: {0}"),
        ("Test_NoActions", "Aucune action n'est définie.", "No action is defined."),
        ("Test_Outcome", "Le fichier serait {0}.", "The file would be {0}."),
        ("Test_Renamed", "renommé en « {0} »", "renamed to “{0}”"),
        ("Test_Moved", "déplacé vers « {0} »", "moved to “{0}”"),
        ("Test_Copied", "copié vers « {0} »", "copied to “{0}”"),
        ("Test_Recycled", "mis à la corbeille", "sent to the recycle bin"),
        ("Test_Deleted", "SUPPRIMÉ DÉFINITIVEMENT", "PERMANENTLY DELETED"),
        ("Test_Command", "la commande « {0} » serait lancée", "the “{0}” command would be run"),

        // ---- Valeurs d'énumération ------------------------------------------------------
        ("Enum_ExtIsOneOf", "est parmi", "is one of"),
        ("Enum_ExtIsNotOneOf", "n'est pas parmi", "is not one of"),
        ("Enum_TargetBase", "sans l'extension", "without the extension"),
        ("Enum_TargetFull", "avec l'extension", "with the extension"),
        ("Enum_Contains", "contient", "contains"),
        ("Enum_StartsWith", "commence par", "starts with"),
        ("Enum_EndsWith", "finit par", "ends with"),
        ("Enum_Equals", "est exactement", "is exactly"),
        ("Enum_Regex", "correspond au motif", "matches the pattern"),
        ("Enum_Created", "de création", "creation"),
        ("Enum_Modified", "de modification", "modification"),
        ("Enum_OlderThan", "remonte à plus de", "is older than"),
        ("Enum_NewerThan", "remonte à moins de", "is newer than"),
        ("Enum_Before", "est avant le", "is before"),
        ("Enum_After", "est après le", "is after"),
        ("Enum_Minutes", "minutes", "minutes"),
        ("Enum_Hours", "heures", "hours"),
        ("Enum_Days", "jours", "days"),
        ("Enum_Weeks", "semaines", "weeks"),
        ("Enum_GreaterThan", "dépasse", "is over"),
        ("Enum_LessThan", "est inférieure à", "is under"),
        ("Enum_EqualTo", "est exactement", "is exactly"),
        ("Enum_Bytes", "octets", "bytes"),
        ("Enum_Kilobytes", "Ko", "KB"),
        ("Enum_Megabytes", "Mo", "MB"),
        ("Enum_Gigabytes", "Go", "GB"),
        ("Enum_KeepBoth", "garder les deux", "keep both"),
        ("Enum_Overwrite", "remplacer", "overwrite"),
        ("Enum_Skip", "ne rien faire", "do nothing"),
        ("Enum_All", "toutes", "all"),
        ("Enum_Any", "au moins une", "at least one"),

        // ---- Catégories de types de fichiers --------------------------------------------
        ("Cat_Images", "Images", "Images"),
        ("Cat_Documents", "Documents", "Documents"),
        ("Cat_Spreadsheets", "Tableurs", "Spreadsheets"),
        ("Cat_Presentations", "Présentations", "Presentations"),
        ("Cat_Videos", "Vidéos", "Videos"),
        ("Cat_Audio", "Audio", "Audio"),
        ("Cat_Archives", "Archives", "Archives"),
        ("Cat_Code", "Code et web", "Code and web"),
        ("Cat_System", "Programmes et système", "Programs and system"),
        ("Cat_Other", "Autres", "Other"),
        ("Type_Unknown", "Fichier .{0}", ".{0} file"),
    ];
}
