<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Banog.Watcher</RootNamespace>
    <AssemblyName>App.Watcher</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Core\App.Core.csproj" />
  </ItemGroup>

</Project>
